### ISSUE TITLE
Store dialogs execution preferences in DB

### ISSUE THREAD

**Issue by wbaccinelli** [PerfectFit-project/virtual-coach-server#275] opened 2022-07-14 08:26 UTC
In preparation phase dialogs the preferences for the administration of execution phase dialogs have to be stored.

- [x] Implement dummy conversation to get the preferences
- [x] Store the preferences in the DB

**Comment by BendikC** [comment] 2022-09-07 15:41
Conversation is mostly implemented, can be run on branch 275 on rasa repo. Typing in 'user preferences' will trigger a form which will remain active until all three slots are filled with correct input. The form is just a dummy conversation but shouldnt require too much adaptation to be actually usable. 
I'm creating a new branch from 275 to work on the DB part as I'm encountering problems with debugging when running it from my local sources. This will have to be merged once the DB part is functional.

**Comment by wbaccinelli** [comment] 2022-09-08 09:37
@BendikC the DB should not need modifications, the table for the preferences is already there. What problems are you encountering?

**Comment by BendikC** [comment] 2022-09-08 13:48
@wbaccinelli I'm not modifying the db. My problem is that rasa isnt responding normally when I run the project locally, it boots up and everything and detects the messages in but doesnt send messages back on the niceday app. This is why Im pushing all my changes to this new branch instead as it functions as intended when I change my docker compose to point to the 275 branch instead of main.
I havent encountered any actual problems for the DB part yet.

**Comment by wbaccinelli** [comment] 2022-09-21 06:43
@BendikC is this issue to be closed and [this branch](https://github.com/PerfectFit-project/virtual-coach-rasa/tree/275-store-dialogs-execution-preferences-in-db) to be merged?

**Comment by BendikC** [comment] 2022-09-28 12:06
Yes I have sent a review request!

**Closed as completed** 2022-11-01 12:40 UTC
